-- WARNING: This DDL can fail.

ALTER TABLE AW_APPROVAL_GROUPS  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE AW_APPROVAL_GROUPS  ADD  SYS_ERR_SVRTY varchar(30);

-- WARNING: This DDL can fail.

ALTER TABLE AW_APPROVALS  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE AW_APPROVALS  ADD  SYS_ERR_SVRTY varchar(30);

-- WARNING: This DDL can fail.

ALTER TABLE AW_DOC_TYPE  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE AW_DOC_TYPE  ADD  SYS_ERR_SVRTY varchar(30);

-- WARNING: This DDL can fail.

ALTER TABLE AW_DOC_INSTANCE  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE AW_DOC_INSTANCE  ADD  SYS_ERR_SVRTY varchar(30);

-- WARNING: This DDL can fail.

ALTER TABLE AW_DOC_ATTR  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE AW_DOC_ATTR  ADD  SYS_ERR_SVRTY varchar(30);

