-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_HM.HIERARCHY  ADD  HIERARCHY_TYPE char(1);

REPLACE VIEW HIERARCHY AS SELECT * FROM UNI_MDM_HM.HIERARCHY ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_HM.HIERARCHY_VER  ADD  HIERARCHY_TYPE char(1);

REPLACE VIEW HIERARCHY_VER AS SELECT * FROM UNI_MDM_HM.HIERARCHY_VER ;

