-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_CODE_SET  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_CODE_SET  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_CODE_SET AS SELECT * FROM UNI_MDM_MST.MST_CODE_SET ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_CUSTOM_CODE_SET_CLM  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_CUSTOM_CODE_SET_CLM  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_CUSTOM_CODE_SET_CLM AS SELECT * FROM UNI_MDM_MST.MST_CUSTOM_CODE_SET_CLM ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_ENTITY_CLASSIFICATION  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_ENTITY_CLASSIFICATION  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_ENTITY_CLASSIFICATION AS SELECT * FROM UNI_MDM_MST.MST_ENTITY_CLASSIFICATION ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_ENTITY_OBJECT  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_ENTITY_OBJECT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_ENTITY_OBJECT AS SELECT * FROM UNI_MDM_MST.MST_ENTITY_OBJECT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_ENTITY_TABLES  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_ENTITY_TABLES  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_ENTITY_TABLES AS SELECT * FROM UNI_MDM_MST.MST_ENTITY_TABLES ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_ENTITY_REL_REFERENCE  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_ENTITY_REL_REFERENCE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_ENTITY_REL_REFERENCE AS SELECT * FROM UNI_MDM_MST.MST_ENTITY_REL_REFERENCE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_ERROR_MASTER  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_ERROR_MASTER  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_ERROR_MASTER AS SELECT * FROM UNI_MDM_MST.MST_ERROR_MASTER ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_GRP_CLASS  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_GRP_CLASS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_GRP_CLASS AS SELECT * FROM UNI_MDM_MST.MST_GRP_CLASS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_LAST_SYNC_UP  ADD  OPERATION_STATUS varchar(40);

ALTER TABLE UNI_MDM_MST.MST_LAST_SYNC_UP  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_LAST_SYNC_UP  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_LAST_SYNC_UP AS SELECT * FROM UNI_MDM_MST.MST_LAST_SYNC_UP ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_MULTITABLE_MAP  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_MULTITABLE_MAP  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_MULTITABLE_MAP AS SELECT * FROM UNI_MDM_MST.MST_MULTITABLE_MAP ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_PSET_PARAMS  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_PSET_PARAMS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_PSET_PARAMS AS SELECT * FROM UNI_MDM_MST.MST_PSET_PARAMS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_PSET_VAL_HDR  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_PSET_VAL_HDR  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_PSET_VAL_HDR AS SELECT * FROM UNI_MDM_MST.MST_PSET_VAL_HDR ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.QUERY_EXECUTION_LOG  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.QUERY_EXECUTION_LOG  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW QUERY_EXECUTION_LOG AS SELECT * FROM UNI_MDM_MST.QUERY_EXECUTION_LOG ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.QUERY_MASTER  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.QUERY_MASTER  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW QUERY_MASTER AS SELECT * FROM UNI_MDM_MST.QUERY_MASTER ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.QUERY_PARAM  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.QUERY_PARAM  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW QUERY_PARAM AS SELECT * FROM UNI_MDM_MST.QUERY_PARAM ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_RELATIONAL_OBJECT  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_RELATIONAL_OBJECT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_RELATIONAL_OBJECT AS SELECT * FROM UNI_MDM_MST.MST_RELATIONAL_OBJECT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_REL_CLM_OBJ_DATA_VAL  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_REL_CLM_OBJ_DATA_VAL  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_REL_CLM_OBJ_DATA_VAL AS SELECT * FROM UNI_MDM_MST.MST_REL_CLM_OBJ_DATA_VAL ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_REL_CLM_OBJ_MAP  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_REL_CLM_OBJ_MAP  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_REL_CLM_OBJ_MAP AS SELECT * FROM UNI_MDM_MST.MST_REL_CLM_OBJ_MAP ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_SYS_PROPS  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_SYS_PROPS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_SYS_PROPS AS SELECT * FROM UNI_MDM_MST.MST_SYS_PROPS ;

CREATE TABLE UNI_MDM_MST.MST_UNI_CUSTOMER (	CUSTOMER_ID	varchar(20)		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_UNI_CUS1_PK PRIMARY KEY(CUSTOMER_ID) 
)  ;

REPLACE VIEW MST_UNI_CUSTOMER AS SELECT * FROM UNI_MDM_MST.MST_UNI_CUSTOMER ;

ALTER TABLE UNI_MDM_MST.MST_UNI_CUSTOMER ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE UNI_MDM_MST.MST_UNI_CUSTOMER ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_VALID_LANGUAGE  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_VALID_LANGUAGE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_VALID_LANGUAGE AS SELECT * FROM UNI_MDM_MST.MST_VALID_LANGUAGE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_VERSION_DETAILS  ADD  VER_STATUS varchar(12);

ALTER TABLE UNI_MDM_MST.MST_VERSION_DETAILS  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_VERSION_DETAILS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_VERSION_DETAILS AS SELECT * FROM UNI_MDM_MST.MST_VERSION_DETAILS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_VERSION_INFO  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_VERSION_INFO  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_VERSION_INFO AS SELECT * FROM UNI_MDM_MST.MST_VERSION_INFO ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_NEXT_NODES  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_NEXT_NODES  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_NEXT_NODES AS SELECT * FROM UNI_MDM_MST.WF_NEXT_NODES ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_NEXT_NODES_AUDIT  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_NEXT_NODES_AUDIT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_NEXT_NODES_AUDIT AS SELECT * FROM UNI_MDM_MST.WF_NEXT_NODES_AUDIT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_PARAMS  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_PARAMS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_PARAMS AS SELECT * FROM UNI_MDM_MST.WF_PARAMS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_PARAMS_AUDIT  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_PARAMS_AUDIT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_PARAMS_AUDIT AS SELECT * FROM UNI_MDM_MST.WF_PARAMS_AUDIT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_PARAMS_EXT  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_PARAMS_EXT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_PARAMS_EXT AS SELECT * FROM UNI_MDM_MST.WF_PARAMS_EXT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_PARAMS_EXT_AUDIT  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_PARAMS_EXT_AUDIT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_PARAMS_EXT_AUDIT AS SELECT * FROM UNI_MDM_MST.WF_PARAMS_EXT_AUDIT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_PROCESS_AUDIT  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_PROCESS_AUDIT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_PROCESS_AUDIT AS SELECT * FROM UNI_MDM_MST.WF_PROCESS_AUDIT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_PROCESS_INSTANCE  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_PROCESS_INSTANCE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_PROCESS_INSTANCE AS SELECT * FROM UNI_MDM_MST.WF_PROCESS_INSTANCE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_PROCESS_NODES  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_PROCESS_NODES  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_PROCESS_NODES AS SELECT * FROM UNI_MDM_MST.WF_PROCESS_NODES ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_PROCESS_NODES_AUDIT  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_PROCESS_NODES_AUDIT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_PROCESS_NODES_AUDIT AS SELECT * FROM UNI_MDM_MST.WF_PROCESS_NODES_AUDIT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_PROCESS_STATUS  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_PROCESS_STATUS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_PROCESS_STATUS AS SELECT * FROM UNI_MDM_MST.WF_PROCESS_STATUS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_PROCESS_TASKS  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_PROCESS_TASKS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_PROCESS_TASKS AS SELECT * FROM UNI_MDM_MST.WF_PROCESS_TASKS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_TASK_AUDIT  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_TASK_AUDIT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_TASK_AUDIT AS SELECT * FROM UNI_MDM_MST.WF_TASK_AUDIT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_WORKFLOWS  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_WORKFLOWS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_WORKFLOWS AS SELECT * FROM UNI_MDM_MST.WF_WORKFLOWS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_GRP_ATTR_SET  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_GRP_ATTR_SET AS SELECT * FROM UNI_MDM_MST.ERR_GRP_ATTR_SET ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_GRP_ATTR_SET_DETAIL  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_GRP_ATTR_SET_DETAIL AS SELECT * FROM UNI_MDM_MST.ERR_GRP_ATTR_SET_DETAIL ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_CLASSIFICATION_ERROR_MAP  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_CLASSIFICATION_ERROR_MAP AS SELECT * FROM UNI_MDM_MST.ERR_CLASSIFICATION_ERROR_MAP ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_CODE_SET  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_CODE_SET AS SELECT * FROM UNI_MDM_MST.ERR_CODE_SET ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_CODE_SET_STATS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_CODE_SET_STATS AS SELECT * FROM UNI_MDM_MST.ERR_CODE_SET_STATS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_XREF_REL  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_XREF_REL AS SELECT * FROM UNI_MDM_MST.ERR_XREF_REL ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_CROSS_REFERENCE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_CROSS_REFERENCE AS SELECT * FROM UNI_MDM_MST.ERR_CROSS_REFERENCE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_CUSTOM_CODE_SET_CLM  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_CUSTOM_CODE_SET_CLM AS SELECT * FROM UNI_MDM_MST.ERR_CUSTOM_CODE_SET_CLM ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_DOMAIN  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_DOMAIN AS SELECT * FROM UNI_MDM_MST.ERR_DOMAIN ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_ENTITY_CLASSIFICATION  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_ENTITY_CLASSIFICATION AS SELECT * FROM UNI_MDM_MST.ERR_ENTITY_CLASSIFICATION ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_ENTITY_OBJECT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_ENTITY_OBJECT AS SELECT * FROM UNI_MDM_MST.ERR_ENTITY_OBJECT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_ENTITY_TABLES  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_ENTITY_TABLES AS SELECT * FROM UNI_MDM_MST.ERR_ENTITY_TABLES ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_ENTITY_REL_REFERENCE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_ENTITY_REL_REFERENCE AS SELECT * FROM UNI_MDM_MST.ERR_ENTITY_REL_REFERENCE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_ERROR_MASTER  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_ERROR_MASTER AS SELECT * FROM UNI_MDM_MST.ERR_ERROR_MASTER ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_GRP_ATTR_VAL_INST  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_GRP_ATTR_VAL_INST AS SELECT * FROM UNI_MDM_MST.ERR_GRP_ATTR_VAL_INST ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_GRP_ATTR_VAL  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_GRP_ATTR_VAL AS SELECT * FROM UNI_MDM_MST.ERR_GRP_ATTR_VAL ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_GRP_CLASS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_GRP_CLASS AS SELECT * FROM UNI_MDM_MST.ERR_GRP_CLASS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_GRP_EXEC_LOG  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_GRP_EXEC_LOG AS SELECT * FROM UNI_MDM_MST.ERR_GRP_EXEC_LOG ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_GRP_MASTER  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_GRP_MASTER AS SELECT * FROM UNI_MDM_MST.ERR_GRP_MASTER ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_GRP_MEMBER  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_GRP_MEMBER AS SELECT * FROM UNI_MDM_MST.ERR_GRP_MEMBER ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_LAST_SYNC_UP  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_LAST_SYNC_UP AS SELECT * FROM UNI_MDM_MST.ERR_LAST_SYNC_UP ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_LOG_ERROR_DATA  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_LOG_ERROR_DATA AS SELECT * FROM UNI_MDM_MST.ERR_LOG_ERROR_DATA ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_MULTITABLE_MAP  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_MULTITABLE_MAP AS SELECT * FROM UNI_MDM_MST.ERR_MULTITABLE_MAP ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_PSET_PARAMS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_PSET_PARAMS AS SELECT * FROM UNI_MDM_MST.ERR_PSET_PARAMS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_PSETVALHDR  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_PSETVALHDR AS SELECT * FROM UNI_MDM_MST.ERR_PSETVALHDR ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_PSETVALUES  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_PSETVALUES AS SELECT * FROM UNI_MDM_MST.ERR_PSETVALUES ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_QUERY_EXECUTION_LOG  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_QUERY_EXECUTION_LOG AS SELECT * FROM UNI_MDM_MST.ERR_QUERY_EXECUTION_LOG ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_QUERY_MASTER  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_QUERY_MASTER AS SELECT * FROM UNI_MDM_MST.ERR_QUERY_MASTER ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_QUERY_PARAM  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_QUERY_PARAM AS SELECT * FROM UNI_MDM_MST.ERR_QUERY_PARAM ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_REFERENCE_CODE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_REFERENCE_CODE AS SELECT * FROM UNI_MDM_MST.ERR_REFERENCE_CODE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_REFERENCE_DESCRIPTION  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_REFERENCE_DESCRIPTION AS SELECT * FROM UNI_MDM_MST.ERR_REFERENCE_DESCRIPTION ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_REL_OBJ_KEY_DESC  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_REL_OBJ_KEY_DESC AS SELECT * FROM UNI_MDM_MST.ERR_REL_OBJ_KEY_DESC ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_REL_OBJ_PROPERTIES  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_REL_OBJ_PROPERTIES AS SELECT * FROM UNI_MDM_MST.ERR_REL_OBJ_PROPERTIES ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_RELATIONAL_OBJECT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_RELATIONAL_OBJECT AS SELECT * FROM UNI_MDM_MST.ERR_RELATIONAL_OBJECT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_REL_CLM_OBJ_DATA_VAL  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_REL_CLM_OBJ_DATA_VAL AS SELECT * FROM UNI_MDM_MST.ERR_REL_CLM_OBJ_DATA_VAL ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_REL_CLM_OBJ_MAP  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_REL_CLM_OBJ_MAP AS SELECT * FROM UNI_MDM_MST.ERR_REL_CLM_OBJ_MAP ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_REL_OBJ_DATA_VAL  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_REL_OBJ_DATA_VAL AS SELECT * FROM UNI_MDM_MST.ERR_REL_OBJ_DATA_VAL ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_RO_FILTER  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_RO_FILTER AS SELECT * FROM UNI_MDM_MST.ERR_RO_FILTER ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_REL_OBJ_KEY_TYPE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_REL_OBJ_KEY_TYPE AS SELECT * FROM UNI_MDM_MST.ERR_REL_OBJ_KEY_TYPE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_REL_OBJ_MAP  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_REL_OBJ_MAP AS SELECT * FROM UNI_MDM_MST.ERR_REL_OBJ_MAP ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_STANDARD_MAP  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_STANDARD_MAP AS SELECT * FROM UNI_MDM_MST.ERR_STANDARD_MAP ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_SYS_PROPS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_SYS_PROPS AS SELECT * FROM UNI_MDM_MST.ERR_SYS_PROPS ;

CREATE TABLE UNI_MDM_MST.ERR_UNI_CUSTOMER (	CUSTOMER_ID	varchar(20)		,
	SYS_TARGET_ID	varchar(10)		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_ERROR_ID	INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 2 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE)		 NOT NULL,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_UPDATED	varchar(15)		,
	SYS_ERROR_TIME	varchar(20)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_DOCUMENT	varchar(100)		 DEFAULT 'UNI_Customer' ,
	SYS_LOAD_ID	varchar(32)		,
	SYS_WORKFLOW_ID	varchar(100)		,
	SYS_VER_ID	INTEGER		, CONSTRAINT ERR_UNI_CUS2_PK PRIMARY KEY(SYS_ERROR_ID) 
)  ;

REPLACE VIEW ERR_UNI_CUSTOMER AS SELECT * FROM UNI_MDM_MST.ERR_UNI_CUSTOMER ;

ALTER TABLE UNI_MDM_MST.ERR_UNI_CUSTOMER ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING','REJECTED') ); 

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_VALID_LANGUAGE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_VALID_LANGUAGE AS SELECT * FROM UNI_MDM_MST.ERR_VALID_LANGUAGE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_VERSION_DETAILS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_VERSION_DETAILS AS SELECT * FROM UNI_MDM_MST.ERR_VERSION_DETAILS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_VERSION_INFO  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_VERSION_INFO AS SELECT * FROM UNI_MDM_MST.ERR_VERSION_INFO ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_NEXT_NODES  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_NEXT_NODES AS SELECT * FROM UNI_MDM_MST.ERR_WF_NEXT_NODES ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_NEXT_NODES_AUDIT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_NEXT_NODES_AUDIT AS SELECT * FROM UNI_MDM_MST.ERR_WF_NEXT_NODES_AUDIT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_PARAMS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_PARAMS AS SELECT * FROM UNI_MDM_MST.ERR_WF_PARAMS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_PARAMS_AUDIT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_PARAMS_AUDIT AS SELECT * FROM UNI_MDM_MST.ERR_WF_PARAMS_AUDIT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_PARAMS_EXT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_PARAMS_EXT AS SELECT * FROM UNI_MDM_MST.ERR_WF_PARAMS_EXT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_PARAMS_EXT_AUDIT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_PARAMS_EXT_AUDIT AS SELECT * FROM UNI_MDM_MST.ERR_WF_PARAMS_EXT_AUDIT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_PROCESS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_PROCESS AS SELECT * FROM UNI_MDM_MST.ERR_WF_PROCESS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_PROCESS_AUDIT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_PROCESS_AUDIT AS SELECT * FROM UNI_MDM_MST.ERR_WF_PROCESS_AUDIT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_PROCESS_INSTANCE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_PROCESS_INSTANCE AS SELECT * FROM UNI_MDM_MST.ERR_WF_PROCESS_INSTANCE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_PROCESS_NODES  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_PROCESS_NODES AS SELECT * FROM UNI_MDM_MST.ERR_WF_PROCESS_NODES ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_PROCESS_NODES_AUDIT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_PROCESS_NODES_AUDIT AS SELECT * FROM UNI_MDM_MST.ERR_WF_PROCESS_NODES_AUDIT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_PROCESS_STATUS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_PROCESS_STATUS AS SELECT * FROM UNI_MDM_MST.ERR_WF_PROCESS_STATUS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_PROCESS_TASKS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_PROCESS_TASKS AS SELECT * FROM UNI_MDM_MST.ERR_WF_PROCESS_TASKS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_TASK_AUDIT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_TASK_AUDIT AS SELECT * FROM UNI_MDM_MST.ERR_WF_TASK_AUDIT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.ERR_WF_WORKFLOWS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW ERR_WF_WORKFLOWS AS SELECT * FROM UNI_MDM_MST.ERR_WF_WORKFLOWS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_GRP_ATTR_SET  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_GRP_ATTR_SET  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_GRP_ATTR_SET AS SELECT * FROM UNI_MDM_MST.MST_GRP_ATTR_SET ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_CLASSIFICATION_ERROR_MAP  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_CLASSIFICATION_ERROR_MAP  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_CLASSIFICATION_ERROR_MAP AS SELECT * FROM UNI_MDM_MST.MST_CLASSIFICATION_ERROR_MAP ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_CODE_SET_STATS  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_CODE_SET_STATS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_CODE_SET_STATS AS SELECT * FROM UNI_MDM_MST.MST_CODE_SET_STATS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_CROSS_REFERENCE  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_CROSS_REFERENCE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_CROSS_REFERENCE AS SELECT * FROM UNI_MDM_MST.MST_CROSS_REFERENCE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_DOMAIN  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_DOMAIN  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_DOMAIN AS SELECT * FROM UNI_MDM_MST.MST_DOMAIN ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_GRP_MASTER  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_GRP_MASTER  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_GRP_MASTER AS SELECT * FROM UNI_MDM_MST.MST_GRP_MASTER ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_PSET_VALUES  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_PSET_VALUES  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_PSET_VALUES AS SELECT * FROM UNI_MDM_MST.MST_PSET_VALUES ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_REFERENCE_CODE  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_REFERENCE_CODE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_REFERENCE_CODE AS SELECT * FROM UNI_MDM_MST.MST_REFERENCE_CODE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_REL_OBJ_KEY_TYPE  ADD  KEY_TYPE char(1);

ALTER TABLE UNI_MDM_MST.MST_REL_OBJ_KEY_TYPE  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_REL_OBJ_KEY_TYPE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_REL_OBJ_KEY_TYPE AS SELECT * FROM UNI_MDM_MST.MST_REL_OBJ_KEY_TYPE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.WF_PROCESS  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.WF_PROCESS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW WF_PROCESS AS SELECT * FROM UNI_MDM_MST.WF_PROCESS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_GRP_ATTR_SET_DETAIL  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_GRP_ATTR_SET_DETAIL  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_GRP_ATTR_SET_DETAIL AS SELECT * FROM UNI_MDM_MST.MST_GRP_ATTR_SET_DETAIL ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_GRP_EXEC_LOG  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_GRP_EXEC_LOG  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_GRP_EXEC_LOG AS SELECT * FROM UNI_MDM_MST.MST_GRP_EXEC_LOG ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_GRP_MEMBER  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_GRP_MEMBER  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_GRP_MEMBER AS SELECT * FROM UNI_MDM_MST.MST_GRP_MEMBER ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_LOG_ERROR_DATA  ADD  MARKED varchar(5);

ALTER TABLE UNI_MDM_MST.MST_LOG_ERROR_DATA  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_LOG_ERROR_DATA  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_LOG_ERROR_DATA AS SELECT * FROM UNI_MDM_MST.MST_LOG_ERROR_DATA ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_REFERENCE_DESCRIPTION  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_REFERENCE_DESCRIPTION  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_REFERENCE_DESCRIPTION AS SELECT * FROM UNI_MDM_MST.MST_REFERENCE_DESCRIPTION ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_REL_OBJ_KEY_DESC  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_REL_OBJ_KEY_DESC  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_REL_OBJ_KEY_DESC AS SELECT * FROM UNI_MDM_MST.MST_REL_OBJ_KEY_DESC ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_REL_OBJ_MAP  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_REL_OBJ_MAP  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_REL_OBJ_MAP AS SELECT * FROM UNI_MDM_MST.MST_REL_OBJ_MAP ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_STANDARD_MAP  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_STANDARD_MAP  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_STANDARD_MAP AS SELECT * FROM UNI_MDM_MST.MST_STANDARD_MAP ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_XREF_REL  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_XREF_REL  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_XREF_REL AS SELECT * FROM UNI_MDM_MST.MST_XREF_REL ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_GRP_ATTR_VAL  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_GRP_ATTR_VAL  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_GRP_ATTR_VAL AS SELECT * FROM UNI_MDM_MST.MST_GRP_ATTR_VAL ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_REL_OBJ_PROPERTIES  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_REL_OBJ_PROPERTIES  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_REL_OBJ_PROPERTIES AS SELECT * FROM UNI_MDM_MST.MST_REL_OBJ_PROPERTIES ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_REL_OBJ_DATA_VAL  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_REL_OBJ_DATA_VAL  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_REL_OBJ_DATA_VAL AS SELECT * FROM UNI_MDM_MST.MST_REL_OBJ_DATA_VAL ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_RO_FILTER  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_RO_FILTER  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_RO_FILTER AS SELECT * FROM UNI_MDM_MST.MST_RO_FILTER ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_MST.MST_GRP_ATTR_VAL_INST  ADD  SYS_ENT_STATE varchar(25);

ALTER TABLE UNI_MDM_MST.MST_GRP_ATTR_VAL_INST  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW MST_GRP_ATTR_VAL_INST AS SELECT * FROM UNI_MDM_MST.MST_GRP_ATTR_VAL_INST ;

