-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_CODE_SET  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_CODE_SET AS SELECT * FROM UNI_MDM_IN.IN_CODE_SET ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_CUSTOM_CODE_SET_CLM  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_CUSTOM_CODE_SET_CLM AS SELECT * FROM UNI_MDM_IN.IN_CUSTOM_CODE_SET_CLM ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_ENTITY_OBJECT  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_ENTITY_OBJECT AS SELECT * FROM UNI_MDM_IN.IN_ENTITY_OBJECT ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_ENTITY_TABLES  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_ENTITY_TABLES AS SELECT * FROM UNI_MDM_IN.IN_ENTITY_TABLES ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_ENTITY_REL_REFERENCE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_ENTITY_REL_REFERENCE AS SELECT * FROM UNI_MDM_IN.IN_ENTITY_REL_REFERENCE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_GRP_CLASS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_GRP_CLASS AS SELECT * FROM UNI_MDM_IN.IN_GRP_CLASS ;

CREATE TABLE UNI_MDM_IN.IN_UNI_CUSTOMER (	CUSTOMER_ID	varchar(20)		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_FILTER	varchar(60)		,
	SYS_WORKFLOW_ID	varchar(100)		, CONSTRAINT IN_UNI_CUSTOMER_PK PRIMARY KEY(CUSTOMER_ID) 
)  ;

REPLACE VIEW IN_UNI_CUSTOMER AS SELECT * FROM UNI_MDM_IN.IN_UNI_CUSTOMER ;

ALTER TABLE UNI_MDM_IN.IN_UNI_CUSTOMER ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_VALID_LANGUAGE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_VALID_LANGUAGE AS SELECT * FROM UNI_MDM_IN.IN_VALID_LANGUAGE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_GRP_ATTR_SET  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_GRP_ATTR_SET AS SELECT * FROM UNI_MDM_IN.IN_GRP_ATTR_SET ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_CODE_SET_STATS  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_CODE_SET_STATS AS SELECT * FROM UNI_MDM_IN.IN_CODE_SET_STATS ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_DOMAIN  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_DOMAIN AS SELECT * FROM UNI_MDM_IN.IN_DOMAIN ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_GRP_MASTER  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_GRP_MASTER AS SELECT * FROM UNI_MDM_IN.IN_GRP_MASTER ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_REFERENCE_CODE  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_REFERENCE_CODE AS SELECT * FROM UNI_MDM_IN.IN_REFERENCE_CODE ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_GRP_ATTR_SET_DETAIL  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_GRP_ATTR_SET_DETAIL AS SELECT * FROM UNI_MDM_IN.IN_GRP_ATTR_SET_DETAIL ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_GRP_EXEC_LOG  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_GRP_EXEC_LOG AS SELECT * FROM UNI_MDM_IN.IN_GRP_EXEC_LOG ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_GRP_MEMBER  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_GRP_MEMBER AS SELECT * FROM UNI_MDM_IN.IN_GRP_MEMBER ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_REFERENCE_DESCRIPTION  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_REFERENCE_DESCRIPTION AS SELECT * FROM UNI_MDM_IN.IN_REFERENCE_DESCRIPTION ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_STANDARD_MAP  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_STANDARD_MAP AS SELECT * FROM UNI_MDM_IN.IN_STANDARD_MAP ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_GRP_ATTR_VAL  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_GRP_ATTR_VAL AS SELECT * FROM UNI_MDM_IN.IN_GRP_ATTR_VAL ;

-- WARNING: This DDL can fail.

ALTER TABLE UNI_MDM_IN.IN_GRP_ATTR_VAL_INST  ADD  SYS_ERR_SVRTY varchar(30);

REPLACE VIEW IN_GRP_ATTR_VAL_INST AS SELECT * FROM UNI_MDM_IN.IN_GRP_ATTR_VAL_INST ;

