CREATE MULTISET TABLE UNI_MDM_VER.VER_TESTDATAALGOCOMPARISON (	SYS_VER_ID	INTEGER		 NOT NULL,
	FIRSTNAME_1	varchar(25)		,
	FIRSTNAME_2	varchar(25)		,
	RANKNUMBER	varchar(25)		,
	MPHONE3_OUTPUT	varchar(25)		,
	MPHONE3_COMPARISON	varchar(25)		,
	DBL_MPHONE_OUTPUT	varchar(25)		,
	DBL_MPHONE_COMPARISON	varchar(25)		,
	SOUNDX_OUTPUT	varchar(25)		,
	SOUNDX_COMPARISON	varchar(25)		,
	SOUNDX_REFINE_OUTPUT	varchar(25)		,
	SOUNDX_REFINE_COMPARISON	varchar(25)		,
	CAVERPHONE_OUTPUT	varchar(25)		,
	CAVERPHONE_COMPARISON	varchar(25)		,
	ID	varchar(5)		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT VER_TESTDAT31_PK PRIMARY KEY(SYS_VER_ID,ID) 
)  ;

REPLACE VIEW VER_TESTDATAALGOCOMPARISON AS SELECT * FROM UNI_MDM_VER.VER_TESTDATAALGOCOMPARISON ;

ALTER TABLE UNI_MDM_VER.VER_TESTDATAALGOCOMPARISON MODIFY  PRIMARY INDEX PARTITION BY (SYS_VER_ID MOD (65534) ) ; 

ALTER TABLE UNI_MDM_VER.VER_TESTDATAALGOCOMPARISON ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE UNI_MDM_VER.VER_TESTDATAALGOCOMPARISON ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

